name: iOS Build Only

on:
  workflow_dispatch:
  push:
    tags:
      - "ios-*"

jobs:
  build-ios:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      # 签出代码
      - uses: actions/checkout@v4
        with:
          ref: master

      # 设置Flutter环境
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.x'
          cache: true

      # 更新Flutter的packages
      - name: Restore packages
        run: |
          cd simple_live_app
          flutter pub get

      # 打包iOS
      - name: Build IPA
        run: |
          cd simple_live_app
          flutter build ios --release --no-codesign

      # 创建未签名ipa
      - name: Create IPA
        run: |
          cd simple_live_app
          mkdir -p build/ios/iphoneos/Payload
          cp -R build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/Runner.app
          cd build/ios/iphoneos/
          zip -q -r ios_no_sign.ipa Payload
          cd ../../..

      # 上传IPA至Artifacts
      - name: Upload IPA to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: |
            simple_live_app/build/ios/iphoneos/ios_no_sign.ipa

      # 创建Release（如果是tag触发）
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          name: "iOS Build ${{ github.ref_name }}"
          body: "iOS无签名版本，可用TrollStore安装"
          files: |
            simple_live_app/build/ios/iphoneos/ios_no_sign.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
